import type { TaxonomyItem } from './positions'

export const CONCEPTS: TaxonomyItem[] = [
  { id: 'framing', name: 'Framing' },
  { id: 'hip_escape', name: 'Hip Escape', aliases: ['shrimping'] },
  { id: 'posture', name: 'Posture' },
  { id: 'base', name: 'Base' },
  { id: 'grip_fighting', name: 'Grip Fighting' },
  { id: 'weight_distribution', name: 'Weight Distribution' },
  { id: 'hip_mobility', name: 'Hip Mobility' },
  { id: 'head_position', name: 'Head Position' },
  { id: 'knee_shield_retention', name: 'Knee Shield Retention' },
  { id: 'underhook', name: 'Underhook' },
  { id: 'overhook', name: 'Overhook', aliases: ['wizzer'] },
  { id: 'cross_face', name: 'Cross Face' },
  { id: 'leg_pummel', name: 'Leg Pummel' },
  { id: 'breaking_grips', name: 'Breaking Grips' },
  { id: 'angle_creation', name: 'Angle Creation' },
  { id: 'pressure_passing', name: 'Pressure Passing' },
  { id: 'speed_passing', name: 'Speed Passing' },
  { id: 'timing', name: 'Timing' },
  { id: 'transitions', name: 'Transitions' },
  { id: 'cardio', name: 'Cardio / Gas Tank' },
  { id: 'mental_pressure', name: 'Mental Pressure' },
  { id: 'rule_awareness', name: 'Rule Awareness' },
  { id: 'point_management', name: 'Point Management' },
  { id: 'stalling_recognition', name: 'Stalling Recognition' },
  { id: 'scramble_efficiency', name: 'Scramble Efficiency' },
  { id: 'recovery_to_guard', name: 'Recovery to Guard' },
  { id: 'top_pressure', name: 'Top Pressure' },
  { id: 'bottom_offense', name: 'Bottom Offense' },
  { id: 'leg_lock_defence', name: 'Leg Lock Defence' },
  { id: 'leg_lock_offense', name: 'Leg Lock Offense' },
  { id: 'takedown_offense', name: 'Takedown Offense' },
  { id: 'takedown_defence', name: 'Takedown Defence' },
  { id: 'finishing_mechanics', name: 'Finishing Mechanics' },
  { id: 'submission_setup', name: 'Submission Setup' },
  { id: 'chain_attacks', name: 'Chain Attacks' },
  { id: 'position_before_submission', name: 'Position Before Submission' },
  { id: 'weight_cutting', name: 'Weight Cutting' },
  { id: 'gas_tank_management', name: 'Gas Tank Management' },
  { id: 'opponent_reading', name: 'Opponent Reading' },
  { id: 'gameplan_adherence', name: 'Gameplan Adherence' },
  { id: 'mat_awareness', name: 'Mat Awareness' },
]

export const CONCEPT_IDS = CONCEPTS.map(c => c.id) as [string, ...string[]]
