ALTER TABLE matches ADD COLUMN IF NOT EXISTS kb_version INTEGER NOT NULL DEFAULT 0;
ALTER TABLE matches ADD COLUMN IF NOT EXISTS kb_upgraded_at TIMESTAMP;
ALTER TABLE matches ADD COLUMN IF NOT EXISTS kb_upgrade_seen_at TIMESTAMP;
ALTER TABLE matches ADD COLUMN IF NOT EXISTS kb_changelog JSONB;
